name: Test, Report Coverage and Release

on: [push, workflow_dispatch]

jobs:
  release:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    if: github.actor == github.repository_owner && (github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, '[ci release]'))

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Get Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
          cache-key: "flutter-:channel:-:version:"
          channel: "stable"

      - name: Get Cached dependencies
        uses: actions/cache@v3
        id: flutter_cache
        with:
          path: ${{ env.PUB_CACHE }}
          key: flutter-dependencies-v1-${{hashFiles('pubspec.yaml', 'pubspec.lock')}}
          restore-keys: |
            flutter-dependencies-v1-

      - name: Populate the Flutter tool's cache of binary artifacts
        if: ${{ steps.flutter_cache.outputs.cache-hit != 'true' }}
        run: |
          flutter config --no-analytics
          flutter precache

      - name: Get Cached .dart_tool
        uses: actions/cache@v3
        id: dart_tool_cache
        with:
          path: .dart_tool
          key: dart-tool-v1-${{hashFiles('pubspec.yaml', 'build.yaml')}}
          restore-keys: |
            dart-tool-v1-

      - name: Decode and save secrets to files
        env:
          ANDROID_SIGNING_KEY: ${{ secrets.ANDROID_SIGNING_KEY }}
          ANDROID_STRINGS: ${{ secrets.ANDROID_STRINGS }}
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
          ANDROID_KEYSTORE_PROPERTIES: ${{ secrets.ANDROID_KEYSTORE_PROPERTIES }}
          ENCRYPTION_KEYS_DART: ${{ secrets.ENCRYPTION_KEYS_DART }}
          SECRETS_DART: ${{ secrets.SECRETS_DART }}
        run: |
          echo $ANDROID_SIGNING_KEY | base64 -d -i > ./android/app/rKey.keystore
          echo $ANDROID_STRINGS | base64 -d -i > ./android/app/src/main/res/values/strings.xml
          echo $GOOGLE_SERVICES_JSON | base64 -d -i > ./android/app/google-services.json
          echo $ANDROID_KEYSTORE_PROPERTIES | base64 -d -i > ./android/releaseKey.properties
          echo $ENCRYPTION_KEYS_DART | base64 -d -i > ./lib/utils/encryption_keys.dart
          echo $SECRETS_DART | base64 -d -i > ./lib/secrets.dart

      - name: Install dependencies
        run: flutter pub get

      - name: Run new builder
        if: ${{ steps.dart_tool_cache.outputs.cache-hit != 'true' }}
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Run cached builder
        if: ${{ steps.dart_tool_cache.outputs.cache-hit == 'true' }}
        run: dart run build_runner build

      - name: Build apk
        run: flutter build apk

      - name: Get version from pubspec.yaml
        id: version
        run: |
          version=$(grep -m 1 'version:' pubspec.yaml | awk '{print $2}' | awk -F "+" '{print $1}')
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Add version to APK filename
        run: |
          mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/app-release-v${{ steps.version.outputs.version }}.apk

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-release-v${{ steps.version.outputs.version }}.apk"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ steps.version.outputs.version }}
          generateReleaseNotes: true
