name: Build and Release app

on: [push, workflow_dispatch]

jobs:
  release-app:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    if: github.actor == github.repository_owner && (github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, '[ci release]') || contains(github.event.head_commit.message, '[ci release google play]'))

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
          pub-cache-key: "flutter-pub-:os:-:channel:-:version:-:arch:"
          cache-key: "flutter-:os:-:channel:-:version:-:arch:"
          channel: "stable"

      - name: Set Up Java
        uses: actions/setup-java@v4
        with:
          cache: "gradle"
          distribution: "corretto"
          java-version: "17"

      - name: Populate the Flutter tool's cache of binary artifacts
        run: |
          flutter config --disable-analytics
          flutter precache

      - name: Decode and save secrets to files
        env:
          ANDROID_SIGNING_KEY: ${{ secrets.ANDROID_SIGNING_KEY }}
          ANDROID_STRINGS: ${{ secrets.ANDROID_STRINGS }}
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
          ANDROID_KEYSTORE_PROPERTIES: ${{ secrets.ANDROID_KEYSTORE_PROPERTIES }}
          ENCRYPTION_KEYS_DART: ${{ secrets.ENCRYPTION_KEYS_DART }}
          SECRETS_DART: ${{ secrets.SECRETS_DART }}
        run: |
          echo $ANDROID_SIGNING_KEY | base64 -d -i > ./android/app/rKey.keystore
          echo $ANDROID_STRINGS | base64 -d -i > ./android/app/src/main/res/values/strings.xml
          echo $GOOGLE_SERVICES_JSON | base64 -d -i > ./android/app/google-services.json
          echo $ANDROID_KEYSTORE_PROPERTIES | base64 -d -i > ./android/releaseKey.properties
          echo $ENCRYPTION_KEYS_DART | base64 -d -i > ./lib/utils/encryption_keys.dart
          echo $SECRETS_DART | base64 -d -i > ./lib/secrets.dart

      - name: Install dependencies
        run: flutter pub get

      - name: Run new builder
        if: ${{ steps.dart_tool_cache.outputs.cache-hit != 'true' }}
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Run cached builder
        if: ${{ steps.dart_tool_cache.outputs.cache-hit == 'true' }}
        run: dart run build_runner build

      - name: Build apk
        run: flutter build apk

      - name: Build app bundle
        run: flutter build appbundle

      - name: Get version from pubspec.yaml
        id: version
        run: |
          version=$(grep -m 1 'version:' pubspec.yaml | awk '{print $2}' | awk -F "+" '{print $1}')
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Get build number from pubspec.yaml
        id: build_number
        run: |
          build_number=$(grep 'version:' pubspec.yaml | awk '{print $2}' | awk -F "+" '{print $2}')
          echo "build_number=$build_number" >> $GITHUB_OUTPUT

      - name: Add version to APK filename
        id: apk_filename
        run: |
          mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/MeetingHelper-v${{ steps.version.outputs.version }}.apk
          echo "value=MeetingHelper-v${{ steps.version.outputs.version }}.apk" >> $GITHUB_OUTPUT

      - name: Get previous version
        id: previous_version
        if: ${{ github.event_name != 'workflow_dispatch' }}
        run: |
          previous_tag=$(git describe --tags --abbrev=0 --match "v[0-9]*.[0-9]*.[0-9]*" $(git rev-list --tags --skip=1 --max-count=1))
          echo "version=${previous_tag#v}" >> $GITHUB_OUTPUT

      - name: Render Release Template
        env:
          NEW_VERSION: ${{ steps.version.outputs.version }}
          NEW_TAG: v${{ steps.version.outputs.version }}
          OLD_TAG: v${{ steps.previous_version.outputs.version }}
          DOWNLOAD_LINK: https://play.google.com/store/apps/details?id=${{vars.PACKAGE_NAME}}
        run: envsubst < ./.github/workflows/release-template.md > release-body.md

      - name: Get release changelog
        id: changelog
        run: |
          echo 'changelog<<EOF' >> $GITHUB_OUTPUT
          git log $(git describe --tags --abbrev=0)...HEAD --format="%H %B" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - name: Output changelog to whats_new
        run: |
          mkdir -p whats_new
          touch whats_new/whatsnew-ar
          git log $(git describe --tags --abbrev=0)...HEAD --format="%B" >> whats_new/whatsnew-ar

      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/${{ steps.apk_filename.outputs.value }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ steps.version.outputs.version }}
          bodyFile: release-body.md

      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: Production
          finalize: true
          version: "${{vars.PACKAGE_NAME}}@${{ steps.version.outputs.version }}+${{ steps.build_number.outputs.build_number }}"

      - name: Upload to Google Play
        if: contains(github.event.head_commit.message, '[ci release google play]')
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
          packageName: ${{vars.PACKAGE_NAME}}
          track: production
          releaseName: v${{ steps.version.outputs.version }}
          whatsNewDirectory: whats_new
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          status: draft
          mappingFile: build/app/outputs/mapping/release/mapping.txt
